accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    # ex: /accounts/login/
    path('login/', views.custom_login, name="login"),
    # ex: /accounts/logout/
    path('logout/', views.custom_logout, name="logout"),
    # ex: /accounts/register/
    path('register/', views.register, name="register"),
    # ex: /accounts/userprofile/
    path('userprofile/', views.update_userprofile, name="userprofile"),
    
]

bbs/urls.py
from django.urls import path

from . import views

app_name = "bbs"
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.QuestionListView.as_view(), name='index'),
    path('my-page', views.my_page, name='my-page'),
    # ex: /bbs/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /bbs/5/reply/
    path('<int:question_id>/reply/', views.reply, name='reply'),
    # ex: /bbs/topic/
    # path('topic/', views.topic, name="topic"),
    path('topic/', views.TopicCreateView.as_view(), name="topic"),
    path('topic-update/', views.TopicUpdateView.as_view(), name="topic-update")
]

up2u_bbs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('bbs/', include('bbs.urls')),
    path('', include('bbs.urls')),
    path('polls/', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbs/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from markdown import markdown


class Question(models.Model):
    question_text = models.CharField('问题', max_length=200)
    # author = models.CharField(max_length=50, default="de8ug")
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE, verbose_name='作者' )
    pub_date = models.DateTimeField('发布时间', auto_now_add=True)
    picture = models.FileField(blank=True, null=True)
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        
    class Meta:
        verbose_name = '问题'
        verbose_name_plural = '问题'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='问题')
    # choice_text = models.CharField(max_length=200)
    choice_text = models.TextField('回复', max_length=2000)
    # author = models.CharField(max_length=50, default="de8ug")
    author = models.ForeignKey(User, default=1, on_delete=models.CASCADE, verbose_name='作者' )
    picture = models.FileField(blank=True, null=True)

    def get_choice_text_md(self):
        return mark_safe(markdown(self.choice_text))

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = '回复'
        verbose_name_plural = '回复'

bbs/forms.py
from django import forms
from .models import Choice, Question


class ChoiceForm(forms.ModelForm):
    choice_text = forms.CharField(
        label="你的答案",
        max_length=2000,
        help_text='最大长度为2000',
        widget=forms.Textarea(
            attrs={
                'placeholder': "请说出你的答案",
                "rows": 8,
                "class": 'form-control'
            }
        )
    )
    picture = forms.FileField(
        label="添加图片(可选)",
        help_text='可以上传的格式: jpg, png',
        required = False,
        widget=forms.FileInput(
            attrs={
                "class": 'form-control'
            }
        )
    )
    class Meta:
        model = Choice
        fields = ['choice_text', 'picture']


class QuestionForm(forms.ModelForm):
    question_text = forms.CharField(
        label="问题",
        max_length=200,
        help_text='最大长度为200',
        widget=forms.TextInput(
            attrs={
                'placeholder': "请输入想问的话题",
                "class": 'form-control'
            }
        )
    )
    picture = forms.FileField(
        label="添加图片(可选)",
        help_text='可以上传的格式: jpg, png',
        required = False,
        widget=forms.FileInput(
            attrs={
                "class": 'form-control'
            }
        )
    )
    class Meta:
        model = Question
        fields = ['question_text', 'picture']

bbs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.views.generic import ListView, CreateView, UpdateView

from .models import Question, Choice
from .forms import ChoiceForm, QuestionForm

# Create your views here.
# FBV: function based view
# CBV: class based view


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')

    query = request.GET.get('q')
    # print(query)
    if query:
        latest_question_list = latest_question_list.filter(
            Q(question_text__icontains=query) |
            Q(author__username__icontains=query)
        ).distinct()

    form = QuestionForm()
    context = {
        'latest_question_list': latest_question_list,
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'form': form
        }
    return render(request, 'bbs/index.html', context)


class QuestionListView(ListView):
    # 数据来源哪个表
    model = Question
    # 从数据库Question表获取所有数据列表的名字
    context_object_name = 'latest_question_list'
    # 渲染模板
    template_name = 'bbs/index.html'
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        # 获取模板上下文变量额外的变量
        context = super().get_context_data(**kwargs)
        context['current_user'] = {
            'user': self.request.user, 
            'is_login': self.request.user.is_authenticated
            }
        context['form'] = QuestionForm()
        print(context)
        return context

    def get_queryset(self):
        # 过滤所获得的数据
        queryset = super().get_queryset()
        print(queryset)
        query = self.request.GET.get('q')
        # print(query)
        if query:
            return queryset.filter(
                Q(question_text__icontains=query) |
                Q(author__username__icontains=query)
            ).distinct()
        return queryset.order_by('-pub_date')


@login_required
def my_page(request):
    latest_question_list = Question.objects.order_by('-pub_date').filter(author=request.user)

    form = QuestionForm()
    context = {
        'latest_question_list': latest_question_list,
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'form': form
        }
    return render(request, 'bbs/my_page.html', context)


def detail(request, question_id):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    form = ChoiceForm()

    question = get_object_or_404(Question, pk=question_id)
    context = {
        'latest_question_list': latest_question_list,
        'question': question,
        'current_user': {'user': request.user, 'is_login': request.user.is_authenticated},
        'form': form
        }
    return render(request, 'bbs/detail.html', context)

@login_required
def topic(request):
    # 取到数据
    if request.method == 'POST':
        # 判断pk存在的情况下，只更新数据
        pk = request.POST.get('pk')
        if pk:
            question = get_object_or_404(Question, pk=pk)
            print('get question by pk: ', pk, question)
            question.question_text = request.POST['question_text']
            question.save()
            return HttpResponseRedirect(reverse('bbs:detail', args=(pk,)))

        form = QuestionForm(request.POST, request.FILES or None)
        print('form:', form, request.FILES)
        # 判断合法，并保存
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
    # 返回页面
    return HttpResponseRedirect(reverse('bbs:index'))


@method_decorator(login_required, name='dispatch')
class TopicUpdateView(UpdateView):
    # 要更新的表
    model = Question
    # 渲染模板
    template_name = 'bbs/detail.html'

    def post(self, request, *args, **kwargs):
        # 如果method为post
        # 判断pk存在的情况下，只更新数据
        pk = request.POST.get('pk')
        if pk:
            question = get_object_or_404(Question, pk=pk)
            question.question_text = request.POST['question_text']
            question.save()
            return HttpResponseRedirect(reverse('bbs:detail', args=(pk,)))


class TopicCreateView(CreateView):
    # 要存入的model
    model = Question
    # 渲染模板
    template_name = 'bbs/index.html'
    # 数据库相应的字段 
    fields = ('question_text', 'picture')

    def form_valid(self, form):
        # 字段合法后会执行这个函数，执行完成后会把字段存入数据库
        """If the form is valid, save the associated model."""
        question = form.save(commit=False)
        question.author = self.request.user
        question.save()
        # 进入表单提交成功的页面
        return redirect('bbs:index')



def reply_old(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        reply_name = request.POST['reply_name']
        reply_text = request.POST['reply_text']
        print(reply_name, reply_text)

        if reply_name and reply_text:
            question.choice_set.create(
                choice_text = reply_text,
                author = reply_name
            )
            question.save()
        else:
            return render(request, 'bbs/detail.html', {
            'question': question,
            'error_message': "没有数据！",
        })
    except (KeyError):
        # Redisplay the question voting form.
        return render(request, 'bbs/detail.html', {
            'question': question,
            'error_message': "传值出错！！",
        })
    else:
        return HttpResponseRedirect(reverse('bbs:detail', args=(question.id,)))

def reply(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        if request.method == 'POST':
            form = ChoiceForm(request.POST, request.FILES or None)
            print('form:', form, request.FILES)
            if form.is_valid():
                reply = form.save(commit=False)
                print('reply: ', reply, type(reply))
                reply.author = request.user
                reply.question = question
                # reply.picture = request.FILES['picture']
                reply.save()

    except (KeyError):
        # Redisplay the question voting form.
        return render(request, 'bbs/detail.html', {
            'question': question,
            'error_message': "传值出错！！",
        })
    else:
        return HttpResponseRedirect(reverse('bbs:detail', args=(question.id,)))

bbs/templates/bbs/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../../../favicon.ico"> -->


    <title>
        UP2U-BBS
        {% block title %}
        
        {% endblock %} 
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/offcanvas.css' %}" rel="stylesheet">

    {% block style %}
        
    {% endblock %} 
  </head>

  <body class="bg-light">

    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="#">UP2U - BBS</a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'bbs:index' %}">首页 <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'bbs:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="关键词或者用户名" aria-label="Search"
          name="q" value="{{ request.GET.q }}">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>
        {% if current_user.is_login %}
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'bbs:my-page' %}">{{ current_user.user }}的主页<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:logout' %}">退出 <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        {% else %}
        <ul class="navbar-nav">
          <li class="nav-item {% block login_active%}{% endblock %}">
            <a class="nav-link" href="{% url 'accounts:login' %}">登录 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item  {% block register_active%}{% endblock %}">
            <a class="nav-link" href="{% url 'accounts:register' %}">注册 <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        {% endif %}
      </div>
    </nav>

    {% block nav-hot %}
    {% endblock %}


<main role="main" class="container">
    {% block content %}

    {% endblock %}
</main>


<script src="{% static 'js/jquery-3.3.1.js' %}"></script>
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
{% block js %}

{% endblock %}

</body>
</html>

bbs/templates/bbs/base_form.html
{% for field in form %}
<div class="form-group">
  <label for="" class="text-light">{{ field.label }}</label>
  <div>{{field}}</div>
  {% for error in field.errors %}
    <div class="field-error">
      {{error}}
    </div>
  {% endfor %}
  <small class="text-black-50">
    {{ field.help_text }}
  </small>
</div>
{% endfor %}

bbs/templates/bbs/detail.html
{% extends 'bbs/base.html' %}
{% load static %}

{% block title %}
| 详情页
{% endblock %} 

{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %} 

{% block nav-hot %}
  <div class="nav-scroller bg-white box-shadow">
    <nav class="nav nav-underline">
      {% for question in latest_question_list %}
        {% if question.choice_set.count > 1 %}
        <a class="nav-link" href="{% url 'bbs:detail' question.id %}">
          {{ question.question_text }}
          <span class="badge badge-pill badge-primary  align-text-bottom">{{ question.choice_set.count }}</span>
        </a>
        {% endif %}
      {% endfor %}
    </nav>
  </div>
{% endblock %}



{% block content %}


        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
    
          <div class="lh-100 row">
            <div class="col-md-8">
                <h6 id="question-text" class="mb-0 text-white lh-100">{{ question.question_text }}</h6>
                <small>{{ question.author }}</small>
                <small>{{ question.pub_date }}</small>
                <span hidden id="question-id">{{ question.id }}</span>
                {% if  question.author == current_user.user%}
                  <button class="btn btn-danger" id="btn-edit-question">编辑</button>
                {% endif %}
            </div>
            <div class="col-md-4">
              {% if question.picture %}
                <img src="{{ question.picture.url }}" alt="question image" class="question-image">
                
              {% endif %}
            </div>
            
          </div>
        </div>

        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 class="border-bottom border-gray pb-2 mb-0">所有回复：</h6>
            {% for c in question.choice_set.all %}
            <div class="media text-muted pt-3">
              <img src="{% static 'img/bs.png' %}" alt="user image" class="mr-2 rounded user-image">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{ c.author }}</strong>
                
                {% if c.picture %}
                <img src="{{ c.picture.url }}" alt="reply-image"  class="reply-image">
                {% endif %}
              </p>
            </div>
                <div class="p-4">
                  {{ c.get_choice_text_md }}
                </div>
            {% endfor %}
        </div>        


<div class="content">

    <div class="reply">
       
        {% if current_user.is_login %}
        <h3 class="text-light">欢迎，{{ current_user.user }}</h3>
        <form action="{% url 'bbs:reply' question.id %}" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
  
                <!-- <label for="reply_text">评论<input type="text" id="reply_text" name="reply_text"></label> -->

                <!-- {{ form.as_p }} -->
              <!-- {% for field in form %}
                <div class="form-group">
                  <label for="">{{ field.label }}</label>
                  <div>{{field}}</div>
                  {% for error in field.errors %}
                    <div class="field-error">
                      {{error}}
                    </div>
                  {% endfor %}
                  <small class="text-black-50">
                    {{ field.help_text }}
                  </small>
                </div>
              {% endfor %} -->
              {% include 'bbs/base_form.html' %}
                <input type="submit" value="提交" class="btn btn-lg btn-secondary btn-block">
                </form>

        {% else%}
        <h3>你没有登录，登录之后才能评论</h3>
        {% endif %}
    </div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</div>


{% endblock %}

{% block js %}
<script src="{% static 'js/edit.js' %}"></script>
<script>
  var mde = new SimpleMDE();
</script>
{% endblock %}

bbs/templates/bbs/index.html
{% extends 'bbs/base.html' %}
{% load static %}

{% block title %}
| 首页
{% endblock %} 

{% block nav-hot %}
  <div class="nav-scroller bg-white box-shadow">
    <nav class="nav nav-underline">
      {% for question in latest_question_list %}
        {% if question.choice_set.count > 1 %}
        <a class="nav-link" href="{% url 'bbs:detail' question.id %}">
          {{ question.question_text }}
          <span class="badge badge-pill badge-primary  align-text-bottom">{{ question.choice_set.count }}</span>
        </a>
        {% endif %}
      {% endfor %}
    </nav>
  </div>
{% endblock %}

{% block content %}

<table class="table table-hover my-3 bg-light">
    <thead>
            <tr class="table-primary">
            <th scope="col">#</th>
            <th scope="col">话题</th>
            <th scope="col">用户</th>
            <th scope="col">发布时间</th>
            <th scope="col">回帖数量</th>
            <th scope="col">最后回帖</th>
            </tr>
    </thead>
    <tbody>
    {% if latest_question_list %}
    {% for question in latest_question_list %}
            <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><span class="title"> <a href="{% url 'bbs:detail' question.id %}">{{ question.question_text }}</a></span></td>
            <td><span>{{ question.author }}</span></td>
            <td><span class="date">{{ question.pub_date|date:"Y-m-d H:i:s" }}</span></td>
            <td><span>{{ question.choice_set.count }}</span></td>
            <td><span>{{ question.choice_set.last.author }}:{{ question.choice_set.last }}</span></td>
            </tr>
            {% endfor %}
    </tbody>
    {% else %}
    <p>没有任何信息</p>
    {% endif %}
    </table>

    {% include 'pagination.html' %}

  <!--new topic-->
  {% if current_user.is_login %}
  <h3>欢迎，{{ current_user.user }}</h3>
  <form action="{% url 'bbs:topic'%}" method="post" enctype="multipart/form-data" novalidate>
          {% csrf_token %}
          
          {% include 'bbs/base_form.html' %}
          <input type="submit" value="提交" class="btn btn-lg btn-secondary btn-block">
    </form>

        {% else%}
        <h3>你没有登录，登录之后才能发布</h3>
        {% endif %}
        ​
{% endblock %}

bbs/templates/bbs/my_page.html
{% extends 'bbs/base.html' %}
{% load static %}

{% block title %}
| {{ current_user.user.username }}的主页
{% endblock %}



{% block nav-hot %}
        <div class="nav-scroller bg-white box-shadow">
                <nav class="nav nav-underline">
                        {% for question in latest_question_list %}
                        {% if question.choice_set.count >= 3 %}
                        <a  class="nav-link" href="{% url 'bbs:detail' question.id %}">{{ question.question_text }}
                        <span class="badge badge-pill badge-primary align-text-bottom">{{ question.choice_set.count }}</span>
                        </a>
                        {% endif %}
                        {% endfor %}
                </nav>
            </div>
{% endblock %}


{% block content %}

<!-- <img src="{% static 'bbs/images/bs.png' %}" alt="test images"> -->

<div class="card">
  <div class="card-header">
      <h3>hi, {{ current_user.user.username }}</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4 offset-md-1 user-image">
        {% if current_user.user.userprofile.picture %}
          <img src="{{ current_user.user.userprofile.picture.url }}" alt="用户头像" class="rounded-circle" width="200" height="200" id="user_picture_img">
        {% else %}
        <img src="{% static 'img/bs.png' %}" alt="用户头像" class="rounded-circle" width="200" height="200" id="user_picture_img">
          {% endif %}
      </div>
      <div class="col">
        <!-- https://www.qdskill.com/docs/bootstrap/docs/4.0/components/forms/
         -->
          <form action="{% url 'accounts:userprofile' %}" method="post" novalidate  enctype="multipart/form-data">
            {% csrf_token %}

              <div class="form-group row">
                  <label for="inputUser" class="col-sm-2 col-form-label">姓名</label>
                  <div class="col-sm-10">
                    <input type="text" readonly class="form-control" id="inputUser" name="username" placeholder="username" value="{{ current_user.user.username }}">
                  </div>
              </div>
              <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">邮箱</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="inputEmail3" name="email" placeholder="Email" value="{{ current_user.user.email }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPhoneNumber" class="col-sm-2 col-form-label">手机</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputPhoneNumber" name="phoneNumber" placeholder="13588888888" value="{{ current_user.user.userprofile.phone_number }}">
                </div>
              </div>
              <fieldset class="form-group">
                <div class="row">
                  <legend class="col-form-label col-sm-2 pt-0">性别</legend>
                  <div class="col-sm-10">
                    <div class="form-check">
                      <!-- <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="1" checked> -->
                      <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="1" 
                      {% if current_user.user.userprofile.sex == '1' %}
                      checked
                      {% endif %}
                      >
                      <label class="form-check-label" for="gridRadios1">
                        男
                      </label>
                    </div>
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="2"
                      {% if current_user.user.userprofile.sex == '2' %}
                      checked
                      {% endif %}
                      >
                      <label class="form-check-label" for="gridRadios2">
                        女
                      </label>
                    </div>
                  </div>
                </div>
              </fieldset>
              <label class="" for="user_picture">
                  选择头像(200x200)
                </label>
              <div class="form-group row">
                  <div class="col-sm-10">
                  <input type="file" name="picture" class="form-control-file" id="user_picture">
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary">更新</button>
                </div>
              </div>
            </form>
      </div>
    </div>
  </div>
</div>

<p class="text-white">你已发布的帖子如下：</p>
<table class="table table-hover my-3 bg-light">
        <thead>
                <tr class="table-primary">
                <th scope="col">#</th>
                <th scope="col">话题</th>
                <th scope="col">发布时间</th>
                <th scope="col">回帖数量</th>
                <th scope="col">最后回帖</th>
                </tr>
        </thead>
        <tbody>
        {% if latest_question_list %}
        {% for question in latest_question_list %}
                <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><span class="title"> <a href="{% url 'bbs:detail' question.id %}">{{ question.question_text }}</a></span></td>
                <td><span class="date">{{ question.pub_date|date:"Y-m-d H:i:s" }}</span></td>
                <td><span>{{ question.choice_set.count }}</span></td>
                <td><span>{{ question.choice_set.last.author }}:{{ question.choice_set.last }}</span></td>
                </tr>
                {% endfor %}
        </tbody>
        {% else %}
        <p>没有任何信息</p>
        {% endif %}
        </table>


{% endblock %}
​

{% block js %}
<script src="{% static 'js/edit.js' %}"></script>
{% endblock %}